
version: '3.8'

services:
  app1:
    build:
      context: ./app1
    environment:
      - PORT=3000
      - ID=App1

  app2:
    build:
      context: ./app2
    environment:
      - PORT=3001
      - ID=App2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2

